"""student attendance table

Revision ID: 1d51c4338ec6
Revises: 4aa71c162b17
Create Date: 2023-01-21 05:29:05.228790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d51c4338ec6'
down_revision = '4aa71c162b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_first_name', sa.String(length=64), nullable=False),
    sa.Column('program', sa.String(length=64), nullable=True),
    sa.Column('cohort', sa.String(length=64), nullable=True),
    sa.Column('program_schedule', sa.String(length=64), nullable=True),
    sa.Column('lesson_number', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('lesson_date', sa.DateTime(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_attendance_student_first_name'), ['student_first_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_attendance_student_first_name'))

    op.drop_table('student_attendance')
    # ### end Alembic commands ###
