"""quiz tables

Revision ID: 213c29d78051
Revises: 7f502940e9cd
Create Date: 2023-03-10 18:50:29.188562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213c29d78051'
down_revision = '7f502940e9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter2_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question1', sa.String(length=64), nullable=False),
    sa.Column('question2', sa.String(length=64), nullable=False),
    sa.Column('question3', sa.String(length=64), nullable=False),
    sa.Column('question4', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter3_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question1', sa.String(length=64), nullable=False),
    sa.Column('question2', sa.String(length=64), nullable=False),
    sa.Column('question3', sa.String(length=64), nullable=False),
    sa.Column('question4', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter4_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question1', sa.String(length=64), nullable=False),
    sa.Column('question2', sa.String(length=64), nullable=False),
    sa.Column('question3', sa.String(length=64), nullable=False),
    sa.Column('question4', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_attendance', schema=None) as batch_op:
        batch_op.drop_index('ix_student_attendance_student_first_name')

    op.drop_table('student_attendance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_attendance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_first_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('program', sa.VARCHAR(length=64), nullable=True),
    sa.Column('cohort', sa.VARCHAR(length=64), nullable=True),
    sa.Column('program_schedule', sa.VARCHAR(length=64), nullable=True),
    sa.Column('lesson_number', sa.INTEGER(), nullable=True),
    sa.Column('hours', sa.INTEGER(), nullable=True),
    sa.Column('lesson_date', sa.DATETIME(), nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_attendance', schema=None) as batch_op:
        batch_op.create_index('ix_student_attendance_student_first_name', ['student_first_name'], unique=False)

    op.drop_table('chapter4_quiz')
    op.drop_table('chapter3_quiz')
    op.drop_table('chapter2_quiz')
    # ### end Alembic commands ###
