"""rename specific fields

Revision ID: 8384db6eaec5
Revises: 1d51c4338ec6
Create Date: 2023-02-27 14:43:14.387099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8384db6eaec5'
down_revision = '1d51c4338ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_residence', sa.String(length=64), nullable=True))
        batch_op.drop_column('residence')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_schedule', sa.String(length=64), nullable=True))
        batch_op.drop_column('program_type')

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_residence', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('current_residence')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_type', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('program_schedule')

    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('residence', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('current_residence')

    # ### end Alembic commands ###
