"""newsletter subscriber table

Revision ID: 93e2da4b0f27
Revises: 68f9f61e83af
Create Date: 2023-03-06 11:27:52.939535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e2da4b0f27'
down_revision = '68f9f61e83af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter__subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('num_newsletter', sa.Integer(), nullable=False),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=False),
    sa.Column('subscription_status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('newsletter__subscriber', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter__subscriber_email'), ['email'], unique=True)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index('ix_client_email')

    op.drop_table('client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), nullable=False),
    sa.Column('num_newsletter', sa.INTEGER(), nullable=False),
    sa.Column('email_confirmed_at', sa.DATETIME(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index('ix_client_email', ['email'], unique=False)

    with op.batch_alter_table('newsletter__subscriber', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter__subscriber_email'))

    op.drop_table('newsletter__subscriber')
    # ### end Alembic commands ###
